# Generated by Django 2.2.6 on 2019-10-10 07:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(
                upload_to='feeds'
            ),
        ),
    ]
